"""Added company field to models

Revision ID: ac4c95de8da9
Revises: 
Create Date: 2025-10-26 18:30:50.478823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4c95de8da9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=200), nullable=False))

    with op.batch_alter_table('stock_levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=200), nullable=False))

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_column('company')

    with op.batch_alter_table('stock_levels', schema=None) as batch_op:
        batch_op.drop_column('company')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('company')

    # ### end Alembic commands ###
